import { ExternalLink, ShieldCheck } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { sources, checkedDate } from '@/components/data/sources';
export default function SourcePanel({ids=[],record}){
 const {data:liveSources=[],isError}=useQuery({queryKey:['technical-sources'],queryFn:()=>base44.entities.TechnicalSource.list('key',100),staleTime:60000});
 const entries=record?(record.source_urls||[]).map(url=>({title:new URL(url).hostname,url,type:record.source_type,scope:record.review_notes})):ids.map(id=>{const live=liveSources.find(s=>s.key===id);return live?{title:live.title,url:live.url,type:live.source_type,scope:live.claim_scope,status:live.verification_status,date:live.date_checked}:sources[id];}).filter(Boolean);
 if(!entries.length)return <div className="panel mt-8 p-5 text-sm text-gray-500">Method: elementary arithmetic on user-entered values. No manufacturer setting is supplied.</div>;
 return <section className="panel mt-8 p-5 md:p-6"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck size={18} className="text-emerald-700"/>Sources & confidence</h2><p className="mt-2 text-xs leading-5 text-gray-500">{record ? `${record.verification_status?.replaceAll('_',' ')} · Last checked: ${record.last_verified||'Unknown'}.` : `Editorial references reviewed ${checkedDate}; individual source status appears below.`} Source review is not physical testing or manufacturer endorsement.</p>{isError&&<p className="mt-3 text-xs text-amber-700">Live source status unavailable. Showing the last published references; confirm the original documentation.</p>}<div className="mt-5 space-y-4">{entries.map(s=><div key={s.url}>{['needs_review','outdated'].includes(s.status)&&<p className="mb-2 text-xs font-bold text-amber-700">Flagged: {s.status.replaceAll('_',' ')} — check current publisher guidance.</p>}<a className="inline-flex items-center gap-2 text-sm font-semibold text-gray-700 hover:text-orange-600" href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={12}/></a><p className="mt-1 text-xs leading-5 text-gray-500">{s.type}{s.date&&` · Checked ${s.date}`}{s.scope&&` · ${s.scope}`}</p></div>)}</div></section>;
}