import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Info, ArrowLeft } from 'lucide-react';
import PageIntro from '@/components/shared/PageIntro';
import SourcePanel from '@/components/shared/SourcePanel';
import ToolForm from '@/components/tools/ToolForm';
import ToolResult from '@/components/tools/ToolResult';
import { tools } from '@/components/data/tools';
import NotFound from '@/pages/NotFound';
export default function ToolDetail(){const {slug}=useParams();const tool=tools.find(t=>t.slug===slug);const [state,setState]=useState(null);if(!tool)return <NotFound/>;const value=state?.slug===slug?state.value:null;const context=new URLSearchParams(window.location.search);const problem=context.get('problem');return <div className="container-page py-10 pb-20"><PageIntro eyebrow={tool.tag} title={tool.fullName} description={tool.description} parent={{name:'Tools',path:'/tools/'}}/>{problem&&<Link to={`/troubleshooting/${encodeURIComponent(problem)}/?${context.toString()}#diagnostic-session`} className="mb-5 inline-flex items-center gap-2 text-sm text-orange-600"><ArrowLeft size={15}/>Return to your diagnosis</Link>}<div className="grid items-start gap-8 lg:grid-cols-[1.4fr_1fr]"><div><ToolForm key={slug} tool={tool} onResult={value=>setState({slug,value})}/>{value&&<div className="mt-6"><ToolResult tool={tool} value={value}/></div>}<section className="mt-8"><h2 className="font-heading text-lg font-bold">How the calculation works</h2><p className="my-4 rounded-lg border border-gray-200 bg-gray-50 p-5 font-mono text-xs leading-6">{tool.formula}</p><p className="body-copy">{tool.how}</p></section></div><aside><div className="panel p-6"><h2 className="text-sm font-bold">Before you begin</h2><p className="body-copy mt-3">{tool.how}</p><div className="mt-6 border-t border-gray-100 pt-5"><h3 className="flex items-center gap-2 text-xs font-bold"><Info size={15} className="text-orange-600"/>Important limitations</h3><p className="mt-3 text-xs leading-6 text-gray-500">{tool.limit}</p></div></div><SourcePanel ids={tool.sources}/><Link to={`/troubleshooting/${tool.problem}/`} className="mt-5 block text-sm font-semibold text-orange-600">Related troubleshooting →</Link></aside></div></div>;}