import { Link, useParams } from 'react-router-dom';
import { CheckCircle2 } from 'lucide-react';
import PageIntro from '@/components/shared/PageIntro';
import SourcePanel from '@/components/shared/SourcePanel';
import DiagnosticSession from '@/components/troubleshooting/DiagnosticSession';
import { problems } from '@/components/data/problems';
import { tools } from '@/components/data/tools';
import { guides } from '@/components/data/guides';
import NotFound from '@/pages/NotFound';
export default function ProblemDetail(){const {slug}=useParams();const p=problems.find(p=>p.slug===slug);if(!p)return <NotFound/>;return <div className="container-page py-10 pb-20"><PageIntro eyebrow="TROUBLESHOOTING FIELD GUIDE" title={`How to fix ${p.name.toLowerCase()}`} description={p.description} parent={{name:'Troubleshooting',path:'/troubleshooting/'}}/><div className="grid items-start gap-8 lg:grid-cols-[1.45fr_1fr]"><div><div className="mb-8 grid gap-6 sm:grid-cols-2"><section><h2 className="font-heading text-lg font-bold">What does it look like?</h2><p className="body-copy mt-3">{p.short}. {p.description}</p></section><section><h2 className="font-heading text-lg font-bold">Common causes to investigate</h2><ul className="mt-3 space-y-2">{p.causes.map(c=><li className="text-sm leading-6 text-gray-500" key={c}>• {c}</li>)}</ul></section></div><DiagnosticSession key={slug} problem={p}/></div><aside><section className="rounded-xl border border-emerald-100 bg-[#f5f8f5] p-6"><h2 className="font-heading text-lg font-bold">Before changing settings</h2><ul className="mt-5 space-y-5">{p.checks.map(c=><li key={c} className="flex gap-3 text-sm leading-6 text-gray-600"><CheckCircle2 size={17} className="mt-1 shrink-0 text-emerald-700"/>{c}</li>)}</ul></section><SourcePanel ids={p.sources}/><div className="panel mt-6 p-6"><h2 className="mb-4 text-sm font-bold">Related tools</h2><div className="space-y-3 text-sm text-orange-600">{[...new Set([p.tool,...tools.filter(t=>t.problem===p.slug).map(t=>t.slug)])].filter(Boolean).map(s=><Link key={s} className="block" to={`/tools/${s}/`}>{tools.find(t=>t.slug===s).name} →</Link>)}<Link className="block" to="/tools/">All calibration tools →</Link></div><h2 className="mb-4 mt-6 text-sm font-bold">Related guides</h2><div className="space-y-3 text-sm text-orange-600">{guides.filter(g=>g.problem===p.slug).map(g=><Link key={g.slug} className="block" to={`/guides/${g.slug}/`}>{g.title} →</Link>)}<Link className="block" to="/guides/">All guides →</Link></div><h2 className="mb-4 mt-6 text-sm font-bold">Catalogs</h2><div className="space-y-3 text-sm text-orange-600"><Link className="block" to="/printers/">Printer documentation →</Link><Link className="block" to="/filaments/">Filament family pages →</Link></div></div></aside></div></div>;}